# Generated by Django 2.1.5 on 2019-02-20 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pretix_sepadebit', '0003_sepaexportorder_payment'),
    ]

    operations = [
        migrations.AddField(
            model_name='sepaexport',
            name='testmode',
            field=models.BooleanField(default=False),
        ),
    ]
