# Generated by Django 2.2 on 2019-04-29 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pretix_sepadebit', '0005_auto_20190429_0811'),
    ]

    operations = [
    ]
