# Generated by Django 4.2.16 on 2025-08-20 11:51

from django.db import migrations
from django.db.models import Exists, OuterRef, Q


def activate_plugin(apps, schema_editor):
    Event = apps.get_model('pretixbase', 'Event')
    Organizer = apps.get_model('pretixbase', 'Organizer')
    SepaExport = apps.get_model('pretix_sepadebit', 'SepaExport')
    qs = Organizer.objects.filter(
        Q(Exists(Event.objects.filter(organizer_id=OuterRef("pk"), plugins__contains="pretix_sepadebit")))
        | Q(Exists(SepaExport.objects.filter(organizer_id=OuterRef("pk"))))
    )
    for org in qs:
        if "pretix_sepadebit" not in org.plugins:
            org.plugins = ",".join(org.plugins.split(",") + ["pretix_sepadebit"])
            org.save(update_fields=["plugins"])


class Migration(migrations.Migration):
    dependencies = [
        ("pretix_sepadebit", "0008_alter_sepaduedate_payment"),
        ("pretixbase", "0287_organizer_plugins"),
    ]

    operations = [
        migrations.RunPython(
            activate_plugin,
            migrations.RunPython.noop,
        )
    ]
