# Generated by Django 4.2.16 on 2025-01-20 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pretix_sepadebit", "0008_alter_sepaduedate_payment"),
    ]

    operations = [
        migrations.AddField(
            model_name="sepaexport",
            name="collection_date",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
